#pragma once

#include <igGapMath.h>
#include <igMath/igVec2f.h>

#include <UI/IHud.h>

class NextGenHUD
{
public:
	enum EHUDRect
	{
		HR_NG_RING_LRG_BACK = HR_COUNT,
		HR_NG_RING_LRG_BORDER,
		HR_NG_RING_MED_BACK,
		HR_NG_RING_MED_BORDER,
		HR_NG_RING_MED_HURT,
		HR_NG_RING_SML_BACK,
		HR_NG_RING_SML_BORDER,
		HR_NG_RING_BAR_BORDER,
		HR_NG_BAR_ENDCAP,
		HR_NG_BAR_CONVEX,
		HR_NG_BAR_CONCAVE,
		HR_NG_BAR_EDGE,
		HR_NG_BAR_FILL,
		HR_NG_ICON_TIMER,
		HR_NG_ICON_ABILITYORB,
		HR_NG_ICON_SCORE,
		HR_NG_BAR_HEALTH,
		HR_NG_BAR_ENERGY,
		HR_NG_BAR_WEAPON,
		HR_NG_BAR_XTREME,
		HR_NG_ARROW,
		HR_NG_RING_LRG_SCAN,
		HR_NG_RING_MED_SCAN,
		HR_NG_RING_SML_SCAN,
		HR_NG_BAR_RAGE,
		HR_NG_RING_MED_BORDER2,
		HR_COUNT,
	};

	NextGenHUD();
};

